### ISSUE TITLE
use of pangeo binder for interactive materials

### ISSUE THREAD

**Issue by scottyhq** [ND-CSE-30151/fall-2020#1]
i've noticed this repository is being used fairly heavily on https://aws-uswest2-binder.pangeo.io . we've made this computing infrastructure public for educational and research needs, so we're happy to see it being used, but would appreciate details about use-cases and needs in this issue https://github.com/pangeo-data/pangeo/issues/440. thanks!  

ping @davidweichiang

**Comment by davidweichiang** [comment]
Sorry, I don't understand. This class ended in Nov 2020.

**Comment by davidweichiang** [comment]
Are you still seeing a lot of usage now? If so, I can change the links so that they don't point to Binder anymore.

**Comment by scottyhq** [comment]
thanks for the response @davidweichiang. yes, every day for the last week there have been multiple sessions active, such as right now: 
```
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d1au7wxlr        1/1     Running   0          139m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d3f5tjwyj        1/1     Running   0          152m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d483btkwk        1/1     Running   0          151m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d4pm510ed        1/1     Running   0          137m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d7owb6uge        1/1     Running   0          140m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2d8hte7s3m        1/1     Running   0          157m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2dayspu369        1/1     Running   0          138m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2dcrg6bnpi        1/1     Running   0          140m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2dgzfzg5yj        1/1     Running   0          150m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2djjxakrvz        1/1     Running   0          153m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2dnhholnaz        1/1     Running   0          136m
prod           jupyter-nd-2dcse-2d30151-2dfall-2d2020-2dslimfh81        1/1     Running   0          142m
```
there are a variety of other options out there for running interactive content such as mybinder.org, google colab. Any particular reason you need the content running on aws out of curiosity? as i mentioned, it's fine to link to your content, we'd just appreciate having more detail on the use case in the issue i linked to above. Also, as an experimental service it can go down at any point.

**Comment by davidweichiang** [comment]
The links do point to mybinder.org.

**Comment by scottyhq** [comment]
gotcha, thanks for the clarification and sorry for the confusion. It just turns out someone is using this particular repo to launch their own computations, since the binder services work the same way, people just have to point to a binder service to get running and they seem to be using ours. I'll close this!
